init:

    image sl_zombie_sprite_LW0607 = im.MatrixColor("source/sl_zombie_sprite_LW0607.webp", im.matrix.tint(0.94, 0.82, 1.0))
    image sl_zombie_sprite2_LW0607 = im.MatrixColor("source/sl_zombie_sprite_LW0607.webp", im.matrix.tint(0.94, 0.82, 1.0))
    image sl_zombie_sprite3_LW0607 = im.MatrixColor("source/sl_zombie_sprite_LW0607.webp", im.matrix.tint(0.94, 0.82, 1.0))
    image sl_zombie_sprite4_LW0607 = im.MatrixColor("source/sl_zombie_sprite_LW0607.webp", im.matrix.tint(0.94, 0.82, 1.0))
    image sl_zombie_sprite5_LW0607 = im.MatrixColor("source/sl_zombie_sprite_LW0607.webp", im.matrix.tint(0.94, 0.82, 1.0))
    image sl_zombie_sprite6_LW0607 = im.MatrixColor("source/sl_zombie_sprite_LW0607.webp", im.matrix.tint(0.94, 0.82, 1.0))
    image sl_zombie_sprite7_LW0607 = im.MatrixColor("source/sl_zombie_sprite_LW0607.webp", im.matrix.tint(0.94, 0.82, 1.0))
    image sl_zombie_sprite8_LW0607 = im.MatrixColor("source/sl_zombie_sprite_LW0607.webp", im.matrix.tint(0.94, 0.82, 1.0))
    image sl_zombie_sprite9_LW0607  = im.MatrixColor("source/sl_zombie_sprite_LW0607.webp", im.matrix.tint(0.94, 0.82, 1.0))
    image hitmarkermlg_LW0607 = "source/hitmarkermlg_LW0607.webp"
    image sl_blkg_LW0607 = "source/sl_blkg_LW0607.webp"
    image dark_LW0607 = "source/dark_LW0607.webp"
    image blood_LW0607 = "source/blood_LW0607.webp"
    image comedysheped = "source/comedysheped.webp"
    image sheped = im.MatrixColor("source/sheped.webp", im.matrix.tint(0.94, 0.82, 1.0))
    image strelok = im.MatrixColor("source/strelok.webp", im.matrix.tint(0.94, 0.82, 1.0))
    image skeetgrustinka = "source/skeetgrustinka.webp"
    image nmall = Image("source/nmall.webp")
    image nmallblur = Image("source/nmall1.webp")
    image traphata = Image("source/traphata.webp")
    image domext = Image("source/2.webp")
    image domint = Image("source/dom1.webp")
    image domintnight = Image("source/dom11.webp")
    image pc = Image("source/pc.webp")
    image propusk = Image("source/propusk.webp")
    image nmallint = Image("source/nmallint.webp")
    image krisa = Image("source/doberman.webp")
    image grena = Image("source/grena.webp")
    image babah = Image("source/babah.webp")
    image novomall = Image("source/mall.webp")
    image deadlylxrd = im.MatrixColor("source/lordspr.webp", im.matrix.tint(0.94, 0.82, 1.0))
    image bergen = im.MatrixColor("source/bergensprite.webp", im.matrix.tint(0.94, 0.82, 1.0))
    image ineony = im.MatrixColor("source/kazahsuka.webp", im.matrix.tint(0.94, 0.82, 1.0))
    image kohnyashvilli = Image("source/kuhshv.webp")
    image kuhnyanight = Image("source/kuhnyanight.webp")
    image kuhnya = Image("source/kuhnya.webp")
    image zaborskit = Image("source/zaborskit.webp")
    image zaborskit1 = Image("source/zaborskit1.webp")
    image zaborskit2 = Image("source/zaborskit2.webp")
    image zaborskit3 = Image("source/zaborskit4.webp")
    image skittolkan = Image("source/skittolkan.webp")
    image skittolkan1 = Image("source/skittolkan1.webp")
    image skittolkan2 = Image("source/skittolkan2.webp")
    image skitupalvtolkan = Image("source/skitupalvtolkan.webp")
    image vannaya = Image("source/vannaya.webp")
    image dristun = Image("source/dristun.webp")
    image morozovcover = Image("source/morozovcover.webp")
    image menushitfade = Image("source/menushitfade.webp")
    image menushitfade0 = Image("source/menushitfade0.webp")
    image menushitfade1 = Image("source/menushitfade1.webp")
    image menushitfade2 = Image("source/menushitfade2.webp")
    image menushitfade3 = Image("source/menushitfade3.webp")
    image menushitfade4 = Image("source/menushitfade4.webp")
    image menushitfade5 = Image("source/menushitfade5.webp")
    image menushitfade6 = Image("source/menushitfade6.webp")
    image menushitfade7 = Image("source/menushitfade7.webp")
    image menushitfade8 = Image("source/menushitfade8.webp")
    image menushitfade9 = Image("source/menushitfade9.webp")
    image menushitfade10 = Image("source/menushitfade10.webp")
    image menushitfadedlc1 = Image("source/menushitfadedcl1.webp")
    image menushitfadedlc2 = Image("source/menushitfadedlc2.webp")
    image menushitfadedlc3 = Image("source/menushitfadedlc3.webp")
    image overlaymenushki = Image("source/overlaymenushki.webp")
    image novoshahtinsk = Image("source/1.webp")
    image hataneonydisk = Image("source/hataneonydisk.webp")
    image m1 = Image("source/m1.webp")
    image m2 = Image("source/m2.webp")
    image m3 = Image("source/m3.webp")
    image m4 = Image("source/m4.webp")
    image m5 = Image("source/m5.webp")
    image lordspr1 = im.MatrixColor("source/lordspr1.webp", im.matrix.tint(0.94, 0.82, 1.0))
    image lordspr2 = im.MatrixColor("source/lordspr2.webp", im.matrix.tint(0.94, 0.82, 1.0))
    image lordspr3 = im.MatrixColor("source/lordspr3.webp", im.matrix.tint(0.94, 0.82, 1.0))
    image bomba = Image("source/bomba.webp")
    image dobermann = im.MatrixColor("source/dobermann.webp", im.matrix.tint(0.94, 0.82, 1.0))
    image bergensvd = im.MatrixColor("source/bergensvd.webp", im.matrix.tint(0.94, 0.82, 1.0))
    image dobermann1 = im.MatrixColor("source/dobermann1.webp", im.matrix.tint(0.94, 0.82, 1.0))
    image dobermann2 = im.MatrixColor("source/dobermann2.webp", im.matrix.tint(0.94, 0.82, 1.0))
    image dobermann3 = im.MatrixColor("source/dobermann3.webp", im.matrix.tint(0.94, 0.82, 1.0))
    image zvukdisk = Image("source/zvukdisk.webp")
    image barman = im.MatrixColor("source/barman.webp", im.matrix.tint(0.94, 0.82, 1.0))
    image bar = Image("source/bar.webp")
    image bergennorm = im.MatrixColor("source/bergennorm.webp", im.matrix.tint(0.94, 0.82, 1.0))
    image basketbol = Image("source/basketbol.webp")
    image avtobusgorit = Image("source/ed_bus_burn.webp")
    image vorotampizda = Image("source/ed_gate_ruined.webp")
    image anim blink_down = "source/blink_down.webp"
    image anim blink_up = "source/blink_up.webp"
    image int_bus = Image("source/int_bus.webp")
    image ext_bus = Image("source/ext_bus.webp")
    image bg ext_bus = Image("source/ext_bus.webp")
    image bg int_catacombs_living1 = Image("source/int_catacombs.webp")
    image bg int_catacombs = Image("source/int_catacombs.webp")
    image bg int_catacombs_hole = Image("source/int_catacombs_hole.webp")
    image bg int_mine = Image("source/int_mine.webp")
    image bg int_mine_room = Image("source/int_mine_room.webp")
    image bg int_mine_coalface = Image("source/int_mine_coalface.webp")
    image bg int_mine_crossroad = Image("source/int_mine_crossroad.webp")
    image bg int_mine_door = Image("source/int_mine_door.webp")
    image bg int_mine_exit_night_light = Image("source/int_mine_exit_night_light.webp")
    image bg int_mine_exit_night_light_ramazan = Image("source/int_mine_exit_night_light_ramazan.webp")
    image bg int_mine_halt = Image("source/int_mine_halt.webp")
    image bg int_musclub_day = Image("source/int_musclub_day.webp")
    image bg int_old_building_night = Image("source/int_old_building_night.webp")
    image bg ext_old_building_sunset = Image("source/ext_old_building_sunset_red_7dl_AMS_XX072020.webp")
    image bg int_clubs_male2_dildo = Image("source/int_clubs_male2_dildo.webp")
    image bg int_clubs_male_day_baza = Image("source/int_clubs_male_day_baza.webp")
    image bg ext_path2_day_posral = Image("source/ext_path2_day_posral.webp")
    image bg ext_path_day = Image("source/ext_path_day.webp")
    image bg ext_path2_day = Image("source/ext_path2_day.webp")
    image bg ext_camp_entrance_day = Image("source/ext_camp_entrance_day.webp")
    image bg ext_road_day = Image("source/ext_road_day.webp")
    image bg ext_clubs_day = Image("source/ext_clubs_day.webp")
    image bg ext_square_night = Image("source/ext_square_night.webp")
    image bg ext_clubs_night = Image("source/ext_clubs_night.webp")
    image bg ext_no_bus_night = Image("source/ext_no_bus_night.webp")
    image bg ext_bus_night = Image("source/ext_bus_night.webp")
    image bg ext_path_night = Image("source/ext_path_night.webp")
    image bg goscar = Image("source/Gosling_and_car_AMS_XX072020.webp")
    image sheped_grust = im.MatrixColor("source/sheped_pechalka.webp", im.matrix.tint(0.94, 0.82, 1.0))
    image pistolpm = im.MatrixColor("source/pmbich.webp", im.matrix.tint(0.94, 0.82, 1.0))
    image pistolpm1 = im.MatrixColor("source/pmbich1.webp", im.matrix.tint(0.94, 0.82, 1.0))
    image pistolpm11 = im.MatrixColor("source/pmbich11.webp", im.matrix.tint(0.94, 0.82, 1.0))
    image blazer = im.MatrixColor("source/blazer.webp", im.matrix.tint(0.94, 0.82, 1.0))
    image pahom = im.MatrixColor("source/pahom.webp", im.matrix.tint(0.94, 0.82, 1.0))
    image pahom1 = im.MatrixColor("source/pahom1.webp", im.matrix.tint(0.94, 0.82, 1.0))
    image pahom2 = im.MatrixColor("source/pahom2.webp", im.matrix.tint(0.94, 0.82, 1.0))
    image pahom3 = im.MatrixColor("source/pahom3.webp", im.matrix.tint(0.94, 0.82, 1.0))
    image bg ext_old_building_night_moonlight = Image("source/ext_old_building_night_moonlight.webp")
    image avelimespr = im.MatrixColor("source/avelime.webp", im.matrix.tint(0.94, 0.82, 1.0))
    image bg ext_playground_day = Image("source/ext_playground_day.webp")
    image bg ext_playground_night = Image("source/ext_playground_night.webp")
    image bg ext_path_sunset = Image("source/ext_path_sunset.webp")
    image smska = im.MatrixColor("source/smska.webp", im.matrix.tint(0.94, 0.82, 1.0))
    image skitscary = Image("source/ed_sem_face_burn.webp")
    image et_rage1 = "source/et_rage1.webp"
    image et_rage2 = "source/et_rage2.webp"
    image et_rage3 = "source/et_rage3.webp"
    image et_rage4 = "source/et_rage4.webp"
    image zatemnenie = Image("source/zatemnenie.webp")
    image eth_pixel = "source/pixel.webp"
    image blood = "source/blood.webp"
    image versiya = "gui/overlay/versiya.webp"
    image int_bus_black = Image("source/int_bus_black.webp")
    image int_bus_night = Image("source/int_bus_night.webp")
    image skitpio = im.MatrixColor("source/skit1.webp", im.matrix.tint(0.94, 0.82, 1.0))
    image skitpio1 = ConditionSwitch(
    "persistent.sprite_time=='sunset'",im.MatrixColor( im.Composite((450,720), (0,0), "source/skit1111.webp"), im.matrix.tint(0.94, 0.82, 1.0) ), 
    "persistent.sprite_time=='night'",im.MatrixColor( im.Composite((450,720), (0,0), "source/skit1111.webp"), im.matrix.tint(0.63, 0.78, 0.82) ), 
    True,im.Composite((450,720), (0,0), "source/skit1111.webp") )
    image sovenok = Image("source/et_camp_enter_dark.webp")
    image sovenokblur = Image("source/et_camp_enter_dark1.webp")
    image sketmon = Image("source/sketmon.webp")
    image ext_bus_night = Image("source/ext_bus_night.webp")
    image slzombar = im.MatrixColor("source/sl_zombie_sprite_LW0607.webp", im.matrix.tint(0.94, 0.82, 1.0))
    image slzombar1 = im.MatrixColor("source/sl_zombie_sprite.webp", im.matrix.tint(0.94, 0.82, 1.0))
    image us_dead = im.MatrixColor("source/us_dead.webp", im.matrix.tint(0.94, 0.82, 1.0))
    image nebo = Image("source/nebo.webp")
    image nebo1 = Image("source/nebo1.webp")
    image nebo2 = Image("source/nebo2.webp")
    image coldspr = im.MatrixColor("source/pip.webp", im.matrix.tint(0.94, 0.82, 1.0))
    image coldspr1 = im.MatrixColor("source/pip1.webp", im.matrix.tint(0.94, 0.82, 1.0))
    image coldsprnight = im.MatrixColor("source/pip11.webp", im.matrix.tint(0.94, 0.82, 1.0))
    image ext_road_night = Image("source/ext_road_night.webp")
    image act1komnata = "source/act1komnata.webp"
    image act1ciga1 = "source/akt1ciga1.webp"
    image akt1ciga2 = "source/akt1ciga2.webp"
    image akt1ciga3 = "source/akt1ciga3.webp"
    image akt1ciga4 = "source/akt1ciga4.webp"
    image akt1ciga5 = "source/akt1ciga5.webp"
    image act1ciga6 = "source/akt1ciga6.webp"
    image act1ciga7 = "source/akt1ciga7.webp"
    image avtoreblansuka = "source/bergensprite.webp"
    image avtoreblansuka1 = "source/bergensprite1.webp"
    image vishel1 = "source/vishel1.webp"
    image vishel2 = "source/vishel2.webp"
    image vishel3 = "source/vishel3.webp"
    image vishel4 = "source/vishel4.webp"
    image vishel5 = "source/vishel5.webp"
    image vishel6 = "source/vishel6.webp"
    image vishel7 = "source/vishel7.webp"
    image vishel8 = "source/vishel8.webp"
    image vishel9 = "source/vishel9.webp"
    image liazik99 = "source/liazik99.webp"
    image melles_spr = "source/melles_spr.webp"
    image dimanspr = "source/diman.webp"
    image dlxrd = "source/lordspr.webp"
    image rmznspr = "source/ramazanshluha.webp"
    image rmznspr1 = "source/ramazanshluha1.webp"
    image ramazan = "source/ramazanchik.webp"
    image porrigeshv = "source/porrige.webp"
    image shstvol1 = im.MatrixColor("source/Crysis_191.webp", im.matrix.tint(0.94, 0.82, 1.0))
    image shstvol11 = im.MatrixColor("source/Crysis_1911.webp", im.matrix.tint(0.94, 0.82, 1.0))
    image SVD_wovystr_LW0607 = "source/SVD_wovystr_LW0607.webp"
    image SVD_svystrel_LW0607 = "source/SVD_svystrel_LW0607.webp"
    image volga = im.MatrixColor("source/volga.webp", im.matrix.tint(0.94, 0.82, 1.0))
    image buhaem = "source/buhaem.webp"
    image coldbuhaet = "source/coldbuhaet.webp"
    image dlya_ebalaMVWWW777 = "source/dlya_ebalaMVWWW777.webp"
    image dlya_ebalaleftMVWWW777 = "source/dlya_ebalaleftMVWWW777.webp"
    image hernya_kakaya_toMVWWW777 = "source/hernya_kakaya_toMVWWW777.webp"
    image trip1MVWWW777 = "source/trip1MVWWW777.webp"
    image trip2MVWWW777 = "source/trip2MVWWW777.webp"
    image trip3MVWWW777 = "source/trip3MVWWW777.webp"
    image skit1 = Image("source/skit11.webp")
    image skit2 = Image("source/skit2.webp")
    image skit3 = Image("source/skit3.webp")
    image nvnight = Image("source/nvnight.webp")
    image ineony = Image("source/ineony.webp")
    image ineony1 = Image("source/ineony1.webp")
    image bergenbook = Image("source/bergenbook.webp")
    image anim_transition_1 = Image("source/anim_transition_1.webp")
    image anim_transition_2 = Image("source/anim_transition_2.webp")
    image anim_transition_3 = Image("source/anim_transition_3.webp")
    image laba = Image("source/laba.webp")
    image lordsprclon1 = im.MatrixColor("source/lordsprclon1.webp", im.matrix.tint(0.94, 0.82, 1.0))
    image lordsprclon2 = im.MatrixColor("source/lordsprclon2.webp", im.matrix.tint(0.94, 0.82, 1.0))
    image lordsprclon3 = im.MatrixColor("source/lordsprclon3.webp", im.matrix.tint(0.94, 0.82, 1.0))
    image lordsprclon4 = im.MatrixColor("source/lordsprclon4.webp", im.matrix.tint(0.94, 0.82, 1.0))
    image skitserun = Image("source/skitserun.webp")
    image skitserun1 = Image("source/skitserun1.webp")
    image vladik-serun2 = Image("source/vladik-serun2.webp")
    image tusa = Image("source/tusa.webp")
    image bergdomint1 = Image("source/bergdomint1.webp")
    image vlados2 = im.MatrixColor("source/vlados2.webp", im.matrix.tint(0.94, 0.82, 1.0))
    image vasilisa = im.MatrixColor("source/vasilisa.webp", im.matrix.tint(0.94, 0.82, 1.0))
    image vasilisanight = im.MatrixColor("source/vasilisanight.webp", im.matrix.tint(0.94, 0.82, 1.0))
    image bar1 = Image("source/bar1.webp")
    image komnata_seksa = Image("source/komnata_seksa.webp")
    image tusaposle = Image("source/tusaposle.webp")
    image labaext = Image("source/labaext.webp")
    image train = Image("source/train.webp")
    image train1 = Image("source/train1.webp")
    image train2 = Image("source/train2.webp")
    image train3 = Image("source/train3.webp")
    image tolkanmall = Image("source/tolkanmall.webp")
    image novomallblya = Image("source/novomallblya.webp")
    image kulak_LW0607 = "source/kulak_LW0607.webp"
    image kulak2_LW0607 = "source/kulak2_LW0607.webp"
    image dlya_ebala_LW0607 = "source/dlya_ebala_LW0607.webp"
    image dlya_ebalaleft_LW0607 = "source/dlya_ebalaleft_LW0607.webp"
    image bg aw_private_ms_1 = "source/aw_private_ms_1.webp"
    image bg aw_private_ms_2 = "source/aw_private_ms_2.webp"
    image bg aw_private_ms_3 = "source/aw_private_ms_3.webp"
    image bg aw_private_ms_4 = "source/aw_private_ms_4.webp"
    image bg aw_private_ms_end = "source/aw_private_ms_end.webp"
    image bg aw_private_r_1 = "source/aw_private_r_1.webp"
    image bg aw_private_r_2 = "source/aw_private_r_2.webp"
    image aw_club_f3 = "source/aw_club_f3.webp"
    image aw_club_f2 = "source/aw_club_f2.webp"
    image aw_club_f1 = "source/aw_club_f1.webp"
    image aw_axe_zam = "source/aw_axe_zam.webp"
    image marat1 = im.MatrixColor("source/marat1.webp", im.matrix.tint(0.94, 0.82, 1.0))
    image sergo1 = im.MatrixColor("source/sergo1.webp", im.matrix.tint(0.94, 0.82, 1.0))
    image sanya1 = im.MatrixColor("source/sanya1.webp", im.matrix.tint(0.94, 0.82, 1.0))
    image marat11 = im.MatrixColor("source/marat11.webp", im.matrix.tint(0.94, 0.82, 1.0))
    image sergo11 = im.MatrixColor("source/sergo11.webp", im.matrix.tint(0.94, 0.82, 1.0))
    image sanya11 = im.MatrixColor("source/sanya11.webp", im.matrix.tint(0.94, 0.82, 1.0))
    image marat12 = im.MatrixColor("source/marat12.webp", im.matrix.tint(0.94, 0.82, 1.0))
    image sergo12 = im.MatrixColor("source/sergo12.webp", im.matrix.tint(0.94, 0.82, 1.0))
    image sanya12 = im.MatrixColor("source/sanya12.webp", im.matrix.tint(0.94, 0.82, 1.0))
    image marat13 = im.MatrixColor("source/marat13.webp", im.matrix.tint(0.94, 0.82, 1.0))
    image sergo13 = im.MatrixColor("source/sergo13.webp", im.matrix.tint(0.94, 0.82, 1.0))
    image sanya13 = im.MatrixColor("source/sanya13.webp", im.matrix.tint(0.94, 0.82, 1.0))
    image scena_leto = "source/scena_leto.webp"
    image scena_leto1 = "source/scena_leto1.webp"
    image pizdavsem2 = im.MatrixColor("source/pizdavsem2.webp", im.matrix.tint(0.94, 0.82, 1.0))
    image pizdavsem = im.MatrixColor("source/pizdavsem1.webp", im.matrix.tint(0.94, 0.82, 1.0))
    image corridor = "source/corridor.webp"
    image zihao = "source/zihao.webp"
    image diskbg = "source/diskbg.webp"
    image sktwarn1 = "source/sktwarn1.webp"
    image sktwarn2 = "source/sktwarn2.webp"
    image diary = "source/diary.webp"
    image nightdvor = "source/nightdvor.webp"
    image tank = ("source/tank.webp")
    image padik = ("source/padik.webp")
    image morozko = ("source/morozko.webp")
    image ddoser = ("source/ddoser.webp")
    image kreslo = ("source/kreslo.webp")
    image kk = ("source/kamera_kazaha.webp")
    image kazahspr = im.MatrixColor("source/kazah.webp", im.matrix.tint(0.94, 0.82, 1.0))
    image harchok = im.MatrixColor("source/harchok.webp", im.matrix.tint(0.94, 0.82, 1.0))
    image vent = ("source/mnd_vent_1.webp")
    image portal = ("source/portal.webp")
    image zagruzka = ("source/zagruzka.webp")
    image nport = ("source/nport.webp")
    image ment = im.MatrixColor("source/ment.webp", im.matrix.tint(0.94, 0.82, 1.0))
    image ment1 = im.MatrixColor("source/ment1.webp", im.matrix.tint(0.94, 0.82, 1.0))
    image bar100 = ("source/bar100.webp")
    image aw_afd_dth1_1 = "source/aw_afd_dth1_1.webp"
    image aw_afd_dth1_2 = "source/aw_afd_dth1_2.webp"
    image aw_afd_dth1_3 = "source/aw_afd_dth1_3.webp"
    image aw_afd_ky1_1 = "source/aw_afd_ky1_1.webp"
    image aw_afd_ky1_2 = "source/aw_afd_ky1_2.webp"
    image aw_afd_ky1_3 = "source/aw_afd_ky1_3.webp"
    image himori = ("source/himori.webp")
    image bg aw_f_cor_1 = "source/aw_f_cor_1.webp"
    image ubratpotomblya = "source/ebanoemenu/menushka_hover.webp"
    image bergenokno = "source/bergenokno.webp"
    image bergenokno1 = "source/bergenokno1.webp"
    image et_road_dark = "source/et_road_dark.webp"
    image bg int_liaz = "source/int_liaz.webp"
    image int_liaz1 = "source/int_liaz1.webp"
    image ivettaspr = im.MatrixColor("source/ivettaspr.webp", im.matrix.tint(0.94, 0.82, 1.0))
    image skitpiohit = im.MatrixColor("source/skitpiohit.webp", im.matrix.tint(0.94, 0.82, 1.0))
